### ISSUE TITLE
Additional items to triage for best practices or spec inclusion

### ISSUE THREAD

**Issue by barbeau** [MobilityData/GTFS_Realtime_Best-Practices#5]
This issue is a staging ground for a checklist for topics that require further community discussion (relocated here from https://github.com/MobilityData/GTFS_Realtime_Best-Practices/pull/1 and https://github.com/MobilityData/Tasks/issues/6#issuecomment-410090345), and likely deserve their own issue.

- [ ] The following belongs in the spec as a "MUST" - If only `delay` is provided in a `stop_time_update` `arrival` or `departure` (and not `time`), then the GTFS [stop_times.txt](https://gtfs.org/reference/static#stopstxt) must contain arrival_times and/or departure_times for these corresponding stops. A `delay` value in the realtime feed is meaningless unless you have a clock time to add it to in the GTFS `stop_times.txt` file.
- [ ] The following belongs in the spec as a "MUST" - Arrival times between sequential stops should always increase - they should never be the same or decrease. Arrival `time` (specified in [StopTimeEvent](#StopTimeEvent)) should be before departure `time`.
- [ ] The following belongs in the spec as a "MUST" - Departure times between sequential stops should always increase - they should never be the same or decrease. Departure`time` (specified in [StopTimeEvent](#StopTimeEvent)) should be after arrival`time`.
- [ ] The following belongs in the spec as a "MUST" - Due to how protocol buffers encode [optional values](https://developers.google.com/protocol-buffers/docs/proto#optional), before reading data from a GTFS Realtime feed consumers should check for the presence of values using the protocol buffer-generated `hasX()` methods before using that value and should only use the value if `hasX()` is true (where `X` is the name of the field). If `hasX()` returns `false`, the default value for that field defined in the `gtfs-realtime.proto` value should be assumed. If the consumer uses the value without checking the `hasX()` method first, it may be reading default data that wasn't intentionally published by the producer.
- [ ] The following describes behavior and should be in the spec - `TripUpdate.delay` should represent schedule deviation, i.e., the observed past value for how ahead/behind schedule the vehicle is. Predictions for future stops should be provided through `StopTimeEvent.delay`
- [ ] The following describes behavior and should be in the spec - If a stop has `schedule_relationship:SKIPPED`, routing results in trip plans will be affected and that stop will not be available to riders.
- [ ] See https://github.com/google/transit/pull/137#issuecomment-457255246 for Google interpretation of Alert `NO_SERVICE`. Should this be in spec? -> If set to `NO_SERVICE`, any route, trip, or stop referenced in the informed_entity will be canceled or closed and will affect trip planning routing results.
- [ ] Metro Transit (Minneapolis) - alerts for stops that are temporarily moved? Do they stay in static? If not alert EntitySelected to stop is orphaned.
- [ ] Include all vehicles (even those not in service) in GTFS-RT feed? Vehicles heading to start a trip should be assigned to the trip they are going to start (?), vehicles that have finished a trip and heading to garage should not appear in feed. Needs discussion - see https://mobilitydata-io.slack.com/archives/C3NH9A9TQ/p1600885187000700.
- [ ] Header timestamp definition - should it be set for each incoming request, or when content was changed, or when provider started gathering content? See https://github.com/google/transit/pull/55 for previous proposal and discussion.
- [ ] Recommended practice for populating various fields for arrival/departure estimates - https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/329
- [ ] Should Service Alert IDs change when alert content changes? - https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/47
- [ ] GTFS-rt feed should meet a minimum HTTP request success rate - https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/113
- [ ] Combine frequency-based (frequencies.txt) trip best practices with content in https://github.com/google/transit/blob/master/gtfs-realtime/spec/en/trip-updates.md#systems-with-repeated-trip_ids
- [ ] Recommendations re: providing/merging VehiclePositions and TripUpdates - Maybe merge Alerts too (TBD pending review of potential conflicts between Alerts and TripUpdates)
    * What do you lose if you don't consume TripUpdates and Alerts, and only consume Vehicle Positions? - see https://docs.google.com/presentation/d/1kWuTupSlS9OJRd9cQAU75s_Ne5Hu8Hca59I6DVLn820/edit?usp=sharing
    * Related to merged feeds being allowed per Google documentation as discussed in https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/330
- [ ] Related to [Should consumers propagate StopTimeUpdates across trips in the same block?](https://github.com/CUTR-at-USF/gtfs-realtime-validator/issues/90) - A best practice saying that if a vehicle will always take a break at a layover (i.e., the layover time shouldn't be subtracted from an delay upstream in the block), then the "trip_B" predictions should be explicitly provided in the GTFS-rt feed.  See [this illustration](https://docs.google.com/presentation/d/1bLV8QaQkGARX1g1ThdQr9mf7oOCGs3db2VH9TsZ-tgw/edit) of propagating delays across trips in the same block.  New rules defining for this are currently an official proposal at https://github.com/google/transit/pull/110, but there are objections to including it in the reference, so Best Practices seems like a good place. 
- [ ] What to do when encounter error? Drop TripUpdate or entire message?
- [ ] Define delineation between TripUpdates being for predictions and VehiclePositions being for observed values (?) - see https://github.com/google/transit/issues/223#issuecomment-737046200
- [ ] Address use of `TripUpdate.delay` - https://github.com/google/transit/issues/223#issuecomment-737283287. Make delay only a prediction and not schedule deviation?
- [ ] Address this ->  "I've been debugging their GTFS-RT feed and it appears that it only produces arrival/departure estimates for either the current stop a bus is at or for the last stop it departed and an arrival estimate for the next stop. This appears to be causing erratic predictions from OBA. Is there a GTFS-RT best practice document that says this is or is not how a GTFS-RT should be outputted?" Suggest separate VehiclePosition schedule_deviation for this case, and don't use predictions? If using predictions in TripUpdate, need to provide for at least the next several stops?
- [ ] Add to spec? -> All `stop_ids` referenced in StopTimeUpdate must have `location_type=0` in `stops.txt` (because GTFS static requires records in stop_times.txt to have `location_type=0` in `stops.txt`).
- [ ] Consider adding more Transit App best practices - https://resources.transit.app/article/182-stop-alerts
- [ ] If you include TripUpdates for more than one trip in a block, the vehicle IDs for those TripUpdates should match if the same vehicle is expected to serve the upcoming trips. If producer doesn't have a vehicle assigned to subsequent trips in a block, it should leave vehicle ID empty in the TripUpdate. (Talk to Sheldon at Cambridge Systematics).
- [ ] Don't include "flex" vehicle positions in VP feeds for vehicles that could potentially visit privacy sensitive locations (e.g., pick someone up at their front door)

When issues are opened for each of these, or they are resolved, this issue can be closed.

**Comment by e-lo** [comment]
@barbeau I think most of these can be checked off/closed?

**Comment by barbeau** [comment]
@e-lo I believe all of the above still need to be addressed. Many of the top items in the checklist are currently in the v1.0 best practices but really should to be escalated into the spec as hard requirements. Other items aren't yet in the best practices because I believe they need more community discussion first. If you see something specific that you think is already addressed in best practices without a need for further work let me know.

**Comment by Sergiodero** [comment]
As GTFS Best Practices (BP) are currently in the process of being merged to the specification, MobilityData is migrating outstanding issues and PRs from this repository to google/transit. Thus, this issue will be closed and further discussion regarding this BP should take place in google/transit. Please refer to [Issue #421](https://github.com/google/transit/issues/421) for a more detailed explanation of the migration process and the proposed next steps. 

With this, we’re hoping to bring more visibility to outstanding BP issues and to restart the discussion around them, so that any improvement that the community finds valuable could be carried forward.
